
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Store
 * 
 */
export type Store = Prisma.StoreModel
/**
 * Model UserStore
 * 
 */
export type UserStore = Prisma.UserStoreModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model CompletedTask
 * 
 */
export type CompletedTask = Prisma.CompletedTaskModel
/**
 * Model Deposit
 * 
 */
export type Deposit = Prisma.DepositModel
/**
 * Model Withdrawal
 * 
 */
export type Withdrawal = Prisma.WithdrawalModel
/**
 * Model ReferralReward
 * 
 */
export type ReferralReward = Prisma.ReferralRewardModel
/**
 * Model AppSettings
 * 
 */
export type AppSettings = Prisma.AppSettingsModel
