
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CompletedTask` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CompletedTask
 * 
 */
export type CompletedTaskModel = runtime.Types.Result.DefaultSelection<Prisma.$CompletedTaskPayload>

export type AggregateCompletedTask = {
  _count: CompletedTaskCountAggregateOutputType | null
  _avg: CompletedTaskAvgAggregateOutputType | null
  _sum: CompletedTaskSumAggregateOutputType | null
  _min: CompletedTaskMinAggregateOutputType | null
  _max: CompletedTaskMaxAggregateOutputType | null
}

export type CompletedTaskAvgAggregateOutputType = {
  earnings: number | null
}

export type CompletedTaskSumAggregateOutputType = {
  earnings: number | null
}

export type CompletedTaskMinAggregateOutputType = {
  id: string | null
  userId: string | null
  taskId: string | null
  status: $Enums.RequestStatus | null
  earnings: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CompletedTaskMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  taskId: string | null
  status: $Enums.RequestStatus | null
  earnings: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CompletedTaskCountAggregateOutputType = {
  id: number
  userId: number
  taskId: number
  status: number
  earnings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CompletedTaskAvgAggregateInputType = {
  earnings?: true
}

export type CompletedTaskSumAggregateInputType = {
  earnings?: true
}

export type CompletedTaskMinAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  earnings?: true
  createdAt?: true
  updatedAt?: true
}

export type CompletedTaskMaxAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  earnings?: true
  createdAt?: true
  updatedAt?: true
}

export type CompletedTaskCountAggregateInputType = {
  id?: true
  userId?: true
  taskId?: true
  status?: true
  earnings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CompletedTaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CompletedTask to aggregate.
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletedTasks to fetch.
   */
  orderBy?: Prisma.CompletedTaskOrderByWithRelationInput | Prisma.CompletedTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CompletedTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletedTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletedTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CompletedTasks
  **/
  _count?: true | CompletedTaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CompletedTaskAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CompletedTaskSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CompletedTaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CompletedTaskMaxAggregateInputType
}

export type GetCompletedTaskAggregateType<T extends CompletedTaskAggregateArgs> = {
      [P in keyof T & keyof AggregateCompletedTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCompletedTask[P]>
    : Prisma.GetScalarType<T[P], AggregateCompletedTask[P]>
}




export type CompletedTaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CompletedTaskWhereInput
  orderBy?: Prisma.CompletedTaskOrderByWithAggregationInput | Prisma.CompletedTaskOrderByWithAggregationInput[]
  by: Prisma.CompletedTaskScalarFieldEnum[] | Prisma.CompletedTaskScalarFieldEnum
  having?: Prisma.CompletedTaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CompletedTaskCountAggregateInputType | true
  _avg?: CompletedTaskAvgAggregateInputType
  _sum?: CompletedTaskSumAggregateInputType
  _min?: CompletedTaskMinAggregateInputType
  _max?: CompletedTaskMaxAggregateInputType
}

export type CompletedTaskGroupByOutputType = {
  id: string
  userId: string
  taskId: string
  status: $Enums.RequestStatus
  earnings: number
  createdAt: Date
  updatedAt: Date
  _count: CompletedTaskCountAggregateOutputType | null
  _avg: CompletedTaskAvgAggregateOutputType | null
  _sum: CompletedTaskSumAggregateOutputType | null
  _min: CompletedTaskMinAggregateOutputType | null
  _max: CompletedTaskMaxAggregateOutputType | null
}

export type GetCompletedTaskGroupByPayload<T extends CompletedTaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CompletedTaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CompletedTaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CompletedTaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CompletedTaskGroupByOutputType[P]>
      }
    >
  >



export type CompletedTaskWhereInput = {
  AND?: Prisma.CompletedTaskWhereInput | Prisma.CompletedTaskWhereInput[]
  OR?: Prisma.CompletedTaskWhereInput[]
  NOT?: Prisma.CompletedTaskWhereInput | Prisma.CompletedTaskWhereInput[]
  id?: Prisma.StringFilter<"CompletedTask"> | string
  userId?: Prisma.StringFilter<"CompletedTask"> | string
  taskId?: Prisma.StringFilter<"CompletedTask"> | string
  status?: Prisma.EnumRequestStatusFilter<"CompletedTask"> | $Enums.RequestStatus
  earnings?: Prisma.FloatFilter<"CompletedTask"> | number
  createdAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}

export type CompletedTaskOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  earnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type CompletedTaskWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CompletedTaskWhereInput | Prisma.CompletedTaskWhereInput[]
  OR?: Prisma.CompletedTaskWhereInput[]
  NOT?: Prisma.CompletedTaskWhereInput | Prisma.CompletedTaskWhereInput[]
  userId?: Prisma.StringFilter<"CompletedTask"> | string
  taskId?: Prisma.StringFilter<"CompletedTask"> | string
  status?: Prisma.EnumRequestStatusFilter<"CompletedTask"> | $Enums.RequestStatus
  earnings?: Prisma.FloatFilter<"CompletedTask"> | number
  createdAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}, "id">

export type CompletedTaskOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  earnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CompletedTaskCountOrderByAggregateInput
  _avg?: Prisma.CompletedTaskAvgOrderByAggregateInput
  _max?: Prisma.CompletedTaskMaxOrderByAggregateInput
  _min?: Prisma.CompletedTaskMinOrderByAggregateInput
  _sum?: Prisma.CompletedTaskSumOrderByAggregateInput
}

export type CompletedTaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.CompletedTaskScalarWhereWithAggregatesInput | Prisma.CompletedTaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.CompletedTaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CompletedTaskScalarWhereWithAggregatesInput | Prisma.CompletedTaskScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CompletedTask"> | string
  userId?: Prisma.StringWithAggregatesFilter<"CompletedTask"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"CompletedTask"> | string
  status?: Prisma.EnumRequestStatusWithAggregatesFilter<"CompletedTask"> | $Enums.RequestStatus
  earnings?: Prisma.FloatWithAggregatesFilter<"CompletedTask"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CompletedTask"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CompletedTask"> | Date | string
}

export type CompletedTaskCreateInput = {
  id?: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCompletedTasksInput
  task: Prisma.TaskCreateNestedOneWithoutCompletedTasksInput
}

export type CompletedTaskUncheckedCreateInput = {
  id?: string
  userId: string
  taskId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCompletedTasksNestedInput
  task?: Prisma.TaskUpdateOneRequiredWithoutCompletedTasksNestedInput
}

export type CompletedTaskUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskCreateManyInput = {
  id?: string
  userId: string
  taskId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskListRelationFilter = {
  every?: Prisma.CompletedTaskWhereInput
  some?: Prisma.CompletedTaskWhereInput
  none?: Prisma.CompletedTaskWhereInput
}

export type CompletedTaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CompletedTaskCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  earnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CompletedTaskAvgOrderByAggregateInput = {
  earnings?: Prisma.SortOrder
}

export type CompletedTaskMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  earnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CompletedTaskMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  earnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CompletedTaskSumOrderByAggregateInput = {
  earnings?: Prisma.SortOrder
}

export type CompletedTaskCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput> | Prisma.CompletedTaskCreateWithoutUserInput[] | Prisma.CompletedTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutUserInput | Prisma.CompletedTaskCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CompletedTaskCreateManyUserInputEnvelope
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
}

export type CompletedTaskUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput> | Prisma.CompletedTaskCreateWithoutUserInput[] | Prisma.CompletedTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutUserInput | Prisma.CompletedTaskCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.CompletedTaskCreateManyUserInputEnvelope
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
}

export type CompletedTaskUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput> | Prisma.CompletedTaskCreateWithoutUserInput[] | Prisma.CompletedTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutUserInput | Prisma.CompletedTaskCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CompletedTaskUpsertWithWhereUniqueWithoutUserInput | Prisma.CompletedTaskUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CompletedTaskCreateManyUserInputEnvelope
  set?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  disconnect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  delete?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  update?: Prisma.CompletedTaskUpdateWithWhereUniqueWithoutUserInput | Prisma.CompletedTaskUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CompletedTaskUpdateManyWithWhereWithoutUserInput | Prisma.CompletedTaskUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
}

export type CompletedTaskUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput> | Prisma.CompletedTaskCreateWithoutUserInput[] | Prisma.CompletedTaskUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutUserInput | Prisma.CompletedTaskCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.CompletedTaskUpsertWithWhereUniqueWithoutUserInput | Prisma.CompletedTaskUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.CompletedTaskCreateManyUserInputEnvelope
  set?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  disconnect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  delete?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  update?: Prisma.CompletedTaskUpdateWithWhereUniqueWithoutUserInput | Prisma.CompletedTaskUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.CompletedTaskUpdateManyWithWhereWithoutUserInput | Prisma.CompletedTaskUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
}

export type CompletedTaskCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput> | Prisma.CompletedTaskCreateWithoutTaskInput[] | Prisma.CompletedTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutTaskInput | Prisma.CompletedTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.CompletedTaskCreateManyTaskInputEnvelope
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
}

export type CompletedTaskUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput> | Prisma.CompletedTaskCreateWithoutTaskInput[] | Prisma.CompletedTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutTaskInput | Prisma.CompletedTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.CompletedTaskCreateManyTaskInputEnvelope
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
}

export type CompletedTaskUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput> | Prisma.CompletedTaskCreateWithoutTaskInput[] | Prisma.CompletedTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutTaskInput | Prisma.CompletedTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.CompletedTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.CompletedTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.CompletedTaskCreateManyTaskInputEnvelope
  set?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  disconnect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  delete?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  update?: Prisma.CompletedTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.CompletedTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.CompletedTaskUpdateManyWithWhereWithoutTaskInput | Prisma.CompletedTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
}

export type CompletedTaskUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput> | Prisma.CompletedTaskCreateWithoutTaskInput[] | Prisma.CompletedTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.CompletedTaskCreateOrConnectWithoutTaskInput | Prisma.CompletedTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.CompletedTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.CompletedTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.CompletedTaskCreateManyTaskInputEnvelope
  set?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  disconnect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  delete?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  connect?: Prisma.CompletedTaskWhereUniqueInput | Prisma.CompletedTaskWhereUniqueInput[]
  update?: Prisma.CompletedTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.CompletedTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.CompletedTaskUpdateManyWithWhereWithoutTaskInput | Prisma.CompletedTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
}

export type EnumRequestStatusFieldUpdateOperationsInput = {
  set?: $Enums.RequestStatus
}

export type CompletedTaskCreateWithoutUserInput = {
  id?: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
  task: Prisma.TaskCreateNestedOneWithoutCompletedTasksInput
}

export type CompletedTaskUncheckedCreateWithoutUserInput = {
  id?: string
  taskId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskCreateOrConnectWithoutUserInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput>
}

export type CompletedTaskCreateManyUserInputEnvelope = {
  data: Prisma.CompletedTaskCreateManyUserInput | Prisma.CompletedTaskCreateManyUserInput[]
}

export type CompletedTaskUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.CompletedTaskUpdateWithoutUserInput, Prisma.CompletedTaskUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.CompletedTaskCreateWithoutUserInput, Prisma.CompletedTaskUncheckedCreateWithoutUserInput>
}

export type CompletedTaskUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.CompletedTaskUpdateWithoutUserInput, Prisma.CompletedTaskUncheckedUpdateWithoutUserInput>
}

export type CompletedTaskUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.CompletedTaskScalarWhereInput
  data: Prisma.XOR<Prisma.CompletedTaskUpdateManyMutationInput, Prisma.CompletedTaskUncheckedUpdateManyWithoutUserInput>
}

export type CompletedTaskScalarWhereInput = {
  AND?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
  OR?: Prisma.CompletedTaskScalarWhereInput[]
  NOT?: Prisma.CompletedTaskScalarWhereInput | Prisma.CompletedTaskScalarWhereInput[]
  id?: Prisma.StringFilter<"CompletedTask"> | string
  userId?: Prisma.StringFilter<"CompletedTask"> | string
  taskId?: Prisma.StringFilter<"CompletedTask"> | string
  status?: Prisma.EnumRequestStatusFilter<"CompletedTask"> | $Enums.RequestStatus
  earnings?: Prisma.FloatFilter<"CompletedTask"> | number
  createdAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CompletedTask"> | Date | string
}

export type CompletedTaskCreateWithoutTaskInput = {
  id?: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCompletedTasksInput
}

export type CompletedTaskUncheckedCreateWithoutTaskInput = {
  id?: string
  userId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskCreateOrConnectWithoutTaskInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput>
}

export type CompletedTaskCreateManyTaskInputEnvelope = {
  data: Prisma.CompletedTaskCreateManyTaskInput | Prisma.CompletedTaskCreateManyTaskInput[]
}

export type CompletedTaskUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.CompletedTaskUpdateWithoutTaskInput, Prisma.CompletedTaskUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.CompletedTaskCreateWithoutTaskInput, Prisma.CompletedTaskUncheckedCreateWithoutTaskInput>
}

export type CompletedTaskUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.CompletedTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.CompletedTaskUpdateWithoutTaskInput, Prisma.CompletedTaskUncheckedUpdateWithoutTaskInput>
}

export type CompletedTaskUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.CompletedTaskScalarWhereInput
  data: Prisma.XOR<Prisma.CompletedTaskUpdateManyMutationInput, Prisma.CompletedTaskUncheckedUpdateManyWithoutTaskInput>
}

export type CompletedTaskCreateManyUserInput = {
  id?: string
  taskId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneRequiredWithoutCompletedTasksNestedInput
}

export type CompletedTaskUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskCreateManyTaskInput = {
  id?: string
  userId: string
  status?: $Enums.RequestStatus
  earnings: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CompletedTaskUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCompletedTasksNestedInput
}

export type CompletedTaskUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CompletedTaskUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumRequestStatusFieldUpdateOperationsInput | $Enums.RequestStatus
  earnings?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CompletedTaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  earnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completedTask"]>

export type CompletedTaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  earnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completedTask"]>

export type CompletedTaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  earnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["completedTask"]>

export type CompletedTaskSelectScalar = {
  id?: boolean
  userId?: boolean
  taskId?: boolean
  status?: boolean
  earnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CompletedTaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "taskId" | "status" | "earnings" | "createdAt" | "updatedAt", ExtArgs["result"]["completedTask"]>
export type CompletedTaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type CompletedTaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type CompletedTaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}

export type $CompletedTaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CompletedTask"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    taskId: string
    status: $Enums.RequestStatus
    earnings: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["completedTask"]>
  composites: {}
}

export type CompletedTaskGetPayload<S extends boolean | null | undefined | CompletedTaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload, S>

export type CompletedTaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CompletedTaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CompletedTaskCountAggregateInputType | true
  }

export interface CompletedTaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CompletedTask'], meta: { name: 'CompletedTask' } }
  /**
   * Find zero or one CompletedTask that matches the filter.
   * @param {CompletedTaskFindUniqueArgs} args - Arguments to find a CompletedTask
   * @example
   * // Get one CompletedTask
   * const completedTask = await prisma.completedTask.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CompletedTaskFindUniqueArgs>(args: Prisma.SelectSubset<T, CompletedTaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CompletedTask that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CompletedTaskFindUniqueOrThrowArgs} args - Arguments to find a CompletedTask
   * @example
   * // Get one CompletedTask
   * const completedTask = await prisma.completedTask.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CompletedTaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CompletedTaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CompletedTask that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskFindFirstArgs} args - Arguments to find a CompletedTask
   * @example
   * // Get one CompletedTask
   * const completedTask = await prisma.completedTask.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CompletedTaskFindFirstArgs>(args?: Prisma.SelectSubset<T, CompletedTaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CompletedTask that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskFindFirstOrThrowArgs} args - Arguments to find a CompletedTask
   * @example
   * // Get one CompletedTask
   * const completedTask = await prisma.completedTask.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CompletedTaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CompletedTaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CompletedTasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CompletedTasks
   * const completedTasks = await prisma.completedTask.findMany()
   * 
   * // Get first 10 CompletedTasks
   * const completedTasks = await prisma.completedTask.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const completedTaskWithIdOnly = await prisma.completedTask.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CompletedTaskFindManyArgs>(args?: Prisma.SelectSubset<T, CompletedTaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CompletedTask.
   * @param {CompletedTaskCreateArgs} args - Arguments to create a CompletedTask.
   * @example
   * // Create one CompletedTask
   * const CompletedTask = await prisma.completedTask.create({
   *   data: {
   *     // ... data to create a CompletedTask
   *   }
   * })
   * 
   */
  create<T extends CompletedTaskCreateArgs>(args: Prisma.SelectSubset<T, CompletedTaskCreateArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CompletedTasks.
   * @param {CompletedTaskCreateManyArgs} args - Arguments to create many CompletedTasks.
   * @example
   * // Create many CompletedTasks
   * const completedTask = await prisma.completedTask.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CompletedTaskCreateManyArgs>(args?: Prisma.SelectSubset<T, CompletedTaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CompletedTasks and returns the data saved in the database.
   * @param {CompletedTaskCreateManyAndReturnArgs} args - Arguments to create many CompletedTasks.
   * @example
   * // Create many CompletedTasks
   * const completedTask = await prisma.completedTask.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CompletedTasks and only return the `id`
   * const completedTaskWithIdOnly = await prisma.completedTask.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CompletedTaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CompletedTaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CompletedTask.
   * @param {CompletedTaskDeleteArgs} args - Arguments to delete one CompletedTask.
   * @example
   * // Delete one CompletedTask
   * const CompletedTask = await prisma.completedTask.delete({
   *   where: {
   *     // ... filter to delete one CompletedTask
   *   }
   * })
   * 
   */
  delete<T extends CompletedTaskDeleteArgs>(args: Prisma.SelectSubset<T, CompletedTaskDeleteArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CompletedTask.
   * @param {CompletedTaskUpdateArgs} args - Arguments to update one CompletedTask.
   * @example
   * // Update one CompletedTask
   * const completedTask = await prisma.completedTask.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CompletedTaskUpdateArgs>(args: Prisma.SelectSubset<T, CompletedTaskUpdateArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CompletedTasks.
   * @param {CompletedTaskDeleteManyArgs} args - Arguments to filter CompletedTasks to delete.
   * @example
   * // Delete a few CompletedTasks
   * const { count } = await prisma.completedTask.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CompletedTaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, CompletedTaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CompletedTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CompletedTasks
   * const completedTask = await prisma.completedTask.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CompletedTaskUpdateManyArgs>(args: Prisma.SelectSubset<T, CompletedTaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CompletedTasks and returns the data updated in the database.
   * @param {CompletedTaskUpdateManyAndReturnArgs} args - Arguments to update many CompletedTasks.
   * @example
   * // Update many CompletedTasks
   * const completedTask = await prisma.completedTask.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CompletedTasks and only return the `id`
   * const completedTaskWithIdOnly = await prisma.completedTask.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CompletedTaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CompletedTaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CompletedTask.
   * @param {CompletedTaskUpsertArgs} args - Arguments to update or create a CompletedTask.
   * @example
   * // Update or create a CompletedTask
   * const completedTask = await prisma.completedTask.upsert({
   *   create: {
   *     // ... data to create a CompletedTask
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CompletedTask we want to update
   *   }
   * })
   */
  upsert<T extends CompletedTaskUpsertArgs>(args: Prisma.SelectSubset<T, CompletedTaskUpsertArgs<ExtArgs>>): Prisma.Prisma__CompletedTaskClient<runtime.Types.Result.GetResult<Prisma.$CompletedTaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CompletedTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskCountArgs} args - Arguments to filter CompletedTasks to count.
   * @example
   * // Count the number of CompletedTasks
   * const count = await prisma.completedTask.count({
   *   where: {
   *     // ... the filter for the CompletedTasks we want to count
   *   }
   * })
  **/
  count<T extends CompletedTaskCountArgs>(
    args?: Prisma.Subset<T, CompletedTaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CompletedTaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CompletedTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CompletedTaskAggregateArgs>(args: Prisma.Subset<T, CompletedTaskAggregateArgs>): Prisma.PrismaPromise<GetCompletedTaskAggregateType<T>>

  /**
   * Group by CompletedTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CompletedTaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CompletedTaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CompletedTaskGroupByArgs['orderBy'] }
      : { orderBy?: CompletedTaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CompletedTaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCompletedTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CompletedTask model
 */
readonly fields: CompletedTaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CompletedTask.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CompletedTaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CompletedTask model
 */
export interface CompletedTaskFieldRefs {
  readonly id: Prisma.FieldRef<"CompletedTask", 'String'>
  readonly userId: Prisma.FieldRef<"CompletedTask", 'String'>
  readonly taskId: Prisma.FieldRef<"CompletedTask", 'String'>
  readonly status: Prisma.FieldRef<"CompletedTask", 'RequestStatus'>
  readonly earnings: Prisma.FieldRef<"CompletedTask", 'Float'>
  readonly createdAt: Prisma.FieldRef<"CompletedTask", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CompletedTask", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CompletedTask findUnique
 */
export type CompletedTaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter, which CompletedTask to fetch.
   */
  where: Prisma.CompletedTaskWhereUniqueInput
}

/**
 * CompletedTask findUniqueOrThrow
 */
export type CompletedTaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter, which CompletedTask to fetch.
   */
  where: Prisma.CompletedTaskWhereUniqueInput
}

/**
 * CompletedTask findFirst
 */
export type CompletedTaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter, which CompletedTask to fetch.
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletedTasks to fetch.
   */
  orderBy?: Prisma.CompletedTaskOrderByWithRelationInput | Prisma.CompletedTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CompletedTasks.
   */
  cursor?: Prisma.CompletedTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletedTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletedTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CompletedTasks.
   */
  distinct?: Prisma.CompletedTaskScalarFieldEnum | Prisma.CompletedTaskScalarFieldEnum[]
}

/**
 * CompletedTask findFirstOrThrow
 */
export type CompletedTaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter, which CompletedTask to fetch.
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletedTasks to fetch.
   */
  orderBy?: Prisma.CompletedTaskOrderByWithRelationInput | Prisma.CompletedTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CompletedTasks.
   */
  cursor?: Prisma.CompletedTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletedTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletedTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CompletedTasks.
   */
  distinct?: Prisma.CompletedTaskScalarFieldEnum | Prisma.CompletedTaskScalarFieldEnum[]
}

/**
 * CompletedTask findMany
 */
export type CompletedTaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter, which CompletedTasks to fetch.
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CompletedTasks to fetch.
   */
  orderBy?: Prisma.CompletedTaskOrderByWithRelationInput | Prisma.CompletedTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CompletedTasks.
   */
  cursor?: Prisma.CompletedTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CompletedTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CompletedTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CompletedTasks.
   */
  distinct?: Prisma.CompletedTaskScalarFieldEnum | Prisma.CompletedTaskScalarFieldEnum[]
}

/**
 * CompletedTask create
 */
export type CompletedTaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * The data needed to create a CompletedTask.
   */
  data: Prisma.XOR<Prisma.CompletedTaskCreateInput, Prisma.CompletedTaskUncheckedCreateInput>
}

/**
 * CompletedTask createMany
 */
export type CompletedTaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CompletedTasks.
   */
  data: Prisma.CompletedTaskCreateManyInput | Prisma.CompletedTaskCreateManyInput[]
}

/**
 * CompletedTask createManyAndReturn
 */
export type CompletedTaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * The data used to create many CompletedTasks.
   */
  data: Prisma.CompletedTaskCreateManyInput | Prisma.CompletedTaskCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CompletedTask update
 */
export type CompletedTaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * The data needed to update a CompletedTask.
   */
  data: Prisma.XOR<Prisma.CompletedTaskUpdateInput, Prisma.CompletedTaskUncheckedUpdateInput>
  /**
   * Choose, which CompletedTask to update.
   */
  where: Prisma.CompletedTaskWhereUniqueInput
}

/**
 * CompletedTask updateMany
 */
export type CompletedTaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CompletedTasks.
   */
  data: Prisma.XOR<Prisma.CompletedTaskUpdateManyMutationInput, Prisma.CompletedTaskUncheckedUpdateManyInput>
  /**
   * Filter which CompletedTasks to update
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * Limit how many CompletedTasks to update.
   */
  limit?: number
}

/**
 * CompletedTask updateManyAndReturn
 */
export type CompletedTaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * The data used to update CompletedTasks.
   */
  data: Prisma.XOR<Prisma.CompletedTaskUpdateManyMutationInput, Prisma.CompletedTaskUncheckedUpdateManyInput>
  /**
   * Filter which CompletedTasks to update
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * Limit how many CompletedTasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CompletedTask upsert
 */
export type CompletedTaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * The filter to search for the CompletedTask to update in case it exists.
   */
  where: Prisma.CompletedTaskWhereUniqueInput
  /**
   * In case the CompletedTask found by the `where` argument doesn't exist, create a new CompletedTask with this data.
   */
  create: Prisma.XOR<Prisma.CompletedTaskCreateInput, Prisma.CompletedTaskUncheckedCreateInput>
  /**
   * In case the CompletedTask was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CompletedTaskUpdateInput, Prisma.CompletedTaskUncheckedUpdateInput>
}

/**
 * CompletedTask delete
 */
export type CompletedTaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
  /**
   * Filter which CompletedTask to delete.
   */
  where: Prisma.CompletedTaskWhereUniqueInput
}

/**
 * CompletedTask deleteMany
 */
export type CompletedTaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CompletedTasks to delete
   */
  where?: Prisma.CompletedTaskWhereInput
  /**
   * Limit how many CompletedTasks to delete.
   */
  limit?: number
}

/**
 * CompletedTask without action
 */
export type CompletedTaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CompletedTask
   */
  select?: Prisma.CompletedTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CompletedTask
   */
  omit?: Prisma.CompletedTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CompletedTaskInclude<ExtArgs> | null
}
